repository:
  has_wiki: false
  delete_branch_on_merge: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false

branches:
  - name: master
    protection:
      restrictions: null
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "CI / test (pull_request)"

labels:
  - name:        auto-changelog
    color:       e01f96
    description: Automatic update of changelog file
  - name:        auto-documentation
    color:       cce1ff
    description: Automatic update of documentation files
  - name:        auto-update
    color:       63d11b
    description: Workflow, documentation templates or configuration files auto-updates
  - name:        breaking-change
    color:       f0ff00
    description: A breaking change that needs to be treated with consideration
  - name:        bug
    color:       d73a4a
    description: Something isn't working
  - name:        dependency-update
    color:       27d14f
    description: A dependency version update
  - name:        documentation
    color:       0075ca
    description: Improvements or additions to documentation
  - name:        duplicate
    color:       cfd3d7
    description: This issue or pull request already exists
  - name:        enhancement
    color:       a2eeef
    description: New feature or request
  - name:        good first issue
    color:       7057ff
    description: Good for newcomers
  - name:        help wanted
    color:       008672
    description: Extra attention is needed
  - name:        invalid
    color:       e4e669
    description: This doesn't seem right
  - name:        question
    color:       d876e3
    description: Further information is requested
  - name:        scala-steward
    color:       c6055c
    description: Dependency auto updates created by scala-steward
  - name:        tests
    color:       04d1c3
    description: Improves or modifies tests
  - name:        wontfix
    color:       ffffff
    description: This will not be worked on
