language: scala
scala:
- 2.11.8

jdk:
- oraclejdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/decrypt-keys.sh; fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage coreJVM/test hammockCirceJVM/test coverageReport
- sbt ++$TRAVIS_SCALA_VERSION clean coreJS/test hammockCirceJS/test exampleJS/compile
- sbt ++$TRAVIS_SCALA_VERSION "docs/tut" "readme/tut"

after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi
