language: scala

scala:
- 2.12.5

jdk:
- oraclejdk8

install:
- rvm use 2.2.8 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1

stages:
- name: test
- name: docs
- name: formatting
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - stage: test
    env: TEST="compile"
    script: scripts/test.sh
  - stage: docs
    env: TEST="docs"
    script: sbt validateDoc
  - stage: formatting
    env: TEST="scalafmt"
    script: sbt validateScalafmt
  - stage: release
    script: sbt ci-release

after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

before_install:
- export PATH=${PATH}:./vendor/bundle
- git fetch --tags
